apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-cont-pod
  name: multi-cont-pod
spec:
  containers:
  - image: busybox
    name: multi-cont-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
