apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: site-data
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: task-pv-claim
